### ISSUE TITLE
Build on Windows fails due to missing pcre DLL

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nightlies#10]
@Araq Please look at https://travis-ci.org/nim-lang/nightlies/jobs/471757924#L8252

```
Hint: operation successful (29250 lines compiled; 1.035 sec total; 47.563MiB peakmem; Debug Build) [SuccessX]
Hint: C:\Users\travis\nimcache\nre_d\runnableExamples\nre_examples1.exe  [Exec]
could not load: pcre64.dll
Error: execution of an external program failed: 'C:\Users\travis\nimcache\nre_d\runnableExamples\nre_examples1.exe '
[Examples] failed: see C:\Users\travis\nimcache\nre_d\runnableExamples\nre_examples1.nim
```

**Comment by kaushalmodi** [comment]
May be all the DLLs from https://nim-lang.org/download/dlls.zip be extracted and placed somewhere from where the Nim tests can pick up?

**Comment by genotrance** [comment]
[AppVeyor](https://github.com/nim-lang/Nim/blob/devel/appveyor.yml#L39) does need pcre64.dll to be copied over, looks like the same applies to Travis.

**Comment by Araq** [comment]
Well, yes, quite possible. :-)

**Comment by kaushalmodi** [comment]
Fixed by @genotrance in https://github.com/nim-lang/nightlies/commit/5d3281fa259eeb69445233122fea9b4c00c2875a.
