### ISSUE TITLE
Fix to show all nightly assets in one release per night

### ISSUE THREAD

**Issue by genotrance** [nim-lang/nightlies#14]
I propose tagging by date and putting the git hashes in the asset filenames instead of in the title and body.

**Comment by kaushalmodi** [comment]
> putting the git hashes in the asset filenames instead of in the title and body.

Note that the asset **title** has to be uniquified.

If not, travis dumps all the assets with the same title under the same release section.. it's quite dumb.

**Comment by genotrance** [comment]
Okay, so you do want to have two release sections per night - one for stable and one for devel?

**Comment by genotrance** [comment]
Yes and your fix will prevent duplicate runs regardless of the name of the tag. Right now, Github creates a tag called untagged-* since we don't set one. Instead, we can either create a tag with the date or with the nim-lang/Nim hash.

I will proceed with two separate releases - one grouping all devel releases under the corresponding hash and a second for stable. It won't retrigger thanks to your fix.

**Comment by kaushalmodi** [comment]
> we can either create a tag with the date or with the nim-lang/Nim hash.

I had tried that (deriving tag names and setting them.. you need to add your git auth keys and stuff for that) and it didn't do something right then. Unfortunately having gone through so many iterations with that tag mess, I failed to add to my notes on the exact problem with that.

Or it could be that whatever that problem was could have been avoided if I had landed up with the https://github.com/nim-lang/nightlies/commit/d925046fe1c855969f9ee3d96e94d65c06ab88ed commit earlier 😄

**Comment by kaushalmodi** [comment]
@genotrance: Thankfully I still have my older attempts in my local git; just pushed it to a branch on my fork. See https://github.com/kaushalmodi/nightlies/commit/6b8ee077c797199165e4f32451e7a3af6bbc6433. Feel free to go through https://github.com/kaushalmodi/nightlies/commits/old-unsquashed and see if you can avoid the mistakes I made then.

**Comment by kaushalmodi** [comment]
@genotrance About doing custom git tags, I faced this: https://github.com/kaushalmodi/nightlies/commit/5198a4742707d85f979b6aa3c205f92cd5613338 -> https://github.com/kaushalmodi/nightlies/commit/7e7f0c11bb6ed7bca0f6ab30893fbaa66be265cd -> https://github.com/kaushalmodi/nightlies/commit/08bd48adaa64edec008c7c6c71ef497b26dec4d6 :)

**Comment by kaushalmodi** [comment]
By a stroke of luck, I just discovered https://github.com/pandoc-extras/pandoc-nightly/blob/master/.travis.yml (Travis CI config for `pandoc` nightly builds) .. see if that helps you.

**Comment by kaushalmodi** [comment]
.. though I am not sure why this `secure` thing: https://github.com/pandoc-extras/pandoc-nightly/blob/4977b86c067d4153a0ce729d05cf9c290674629a/.travis.yml#L107 is commited in plain text 😕

**Comment by genotrance** [comment]
I believe this is fixed.
