### ISSUE TITLE
Create Linux binaries using Holy Build Box

### ISSUE THREAD

**Issue by genotrance** [nim-lang/nightlies#22]
I've been able to create generic Linux binaries that work across distributions using HBB. Scripts are posted here:

https://gist.github.com/genotrance/8789260aff1570c7c5fe930eaba7ce33

Right now, the script takes an input xz file and outputs an xz file with binaries created within. This is accomplished within Docker and should be very easy to integrate into nightlies.

No major impacts - instead of using testinstall which does a rebuild and test, we can simply use hbb to rebuild the xz with the binaries and then run only the extract and test steps in Travis. No need to use testinstall on Linux anymore and no code changes needed in koch to accomplish any of this. No major build time impact expected.

Alternative is to update koch testinstall to not rebuild if binaries are already present in the xz but I leave it up to @Araq to decide. The impact is minimal in either case.

Question though - why does testinstall run csources and xz [again](https://github.com/nim-lang/Nim/blob/devel/koch.nim#L528)? Looks like we do it twice now, I think we should remove from testinstall and leave it in [Travis](https://github.com/nim-lang/nightlies/blob/master/.travis.yml#L150) since it will allow us to run hbb after the xz step but before testinstall.

**Comment by genotrance** [comment]
Note - we will have to add Linux 32-bit build to the matrix for this feature. It will mean one more job and resulting binary uploaded to the releases page.

**Comment by Araq** [comment]
Well there might be redundancy in the process. The point is to unzip the ``.tar.xz`` and run some tests on it. There is little need to test things before the tar.xz is produced.

> Alternative is to update koch testinstall to not rebuild if binaries are already present in the xz but I leave it up to @Araq to decide. The impact is minimal in either case.

I don't know, in general I prefer the logic to be in koch.nim rather than in Bash files. But it's really up to you, do what you think is best, you're doing a great job! :-)

**Comment by genotrance** [comment]
This is done and binaries have been posted. It will be cool to share the news somewhere and start encouraging people to use them instead of building from scratch in CI.

**Comment by Araq** [comment]
Post on the forum please?
