### ISSUE TITLE
use Azure Pipelines YAML CD?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/nightlies#32]
this was just released yesterday: https://devblogs.microsoft.com/devops/announcing-general-availability-of-azure-pipelines-yaml-cd/

eg it allows release pipelines configured in YAML like the rest of CI; given that azure pipelines has nice advantages over travis/appveyor (eg more parallelism), I'm wondering whether this could be used. Feel free to close if not.

**Comment by narimiran** [comment]
> this was just released **yesterday**

IMO, let's not be early adopters (read: beta testers) :)

But at some point in the future we might want to switch if @alaviss and @genotrance give their blessing.

**Comment by alaviss** [comment]
I actually got a Github Actions based version [here](https://github.com/alaviss/nightlies/actions/runs/69420394). Development is stopped at the moment though, but I might come back to it in the future.

**Comment by alaviss** [comment]
I think this can now be closed.
