### ISSUE TITLE
[$300] Move CI pipeline to Github Actions

### ISSUE THREAD

**Issue by alaviss** [nim-lang/nightlies#33]
This should drastically speed up our builds with more concurrent jobs, and with an overall cleaner architecture to manage.

I have got an experimental setup here: https://github.com/alaviss/nightlies/actions, though it's not working yet. However parts of the pipeline architecture has already been successfully applied to [fusion](https://github.com/nim-lang/fusion).

I'm planning a two-stage pipeline:

- Stage 1: Generate generic source package, nothing too fancy here, just a `.tar.xz` archive like the one we offer on our [website](https://nim-lang.org/install_unix.html).

- Stage 2: Build and generate binary packages from the source generated earlier: This should let us catch any source packaging issues early on. The resulting binaries will then be released as nightlies.

This should give us comparable result with our current pipeline, though the current one is inefficient as it redo stage 1 for every arch/os combo.

With this more modular pipeline, we can also add more stages to test the generated binary packages themselves, avoiding possible issues before release.

/cc @Araq @narimiran @genotrance

**Comment by narimiran** [comment]
@alaviss we labeled this issue as a `Bounty` with a $300 reward.

Once you implement it, click on 'Submit Expense' on [our OpenCollective page](https://opencollective.com/Nim) and follow [these instructions](https://docs.opencollective.com/help/v/master/expenses/submitting-expenses).

**Comment by alaviss** [comment]
Submitted expense https://opencollective.com/nim/expenses/22695
