### ISSUE TITLE
Add 'koch testinstall' for linux/osx

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nightlies#4]
https://gitter.im/nim-lang/Nim?at=5bc9004d069fca52a5598a63

**Comment by kaushalmodi** [comment]
@Araq I tried adding `koch testinstall`, but it is failing with this error:

```
./koch tests
bin/nim cc --taintMode:on --opt:speed testament/tester
Error: unhandled exception: No such file or directory [OSError]
FAILURE
FAILURE
```

[Full log][0] - *Search for `[phase 6` to directly reach the `koch testinstall` part.

[0]: https://api.travis-ci.org/v3/job/443499823/log.txt

**Comment by kaushalmodi** [comment]
Looks like the `testament/` dir is not getting packed into the tar.xz at all.

**Comment by kaushalmodi** [comment]
Ref: https://github.com/nim-lang/Nim/commit/00f84d3d22cdeed7b4a2060e6307e3a742729055

**Comment by kaushalmodi** [comment]
@genotrance The initial goal for the nighties will be considered "done" once "koch testinstall" passed on all platforms. If you don't get to this earlier, I'll try running "koch testinstall" later today to see it has now started passing.

**Comment by kaushalmodi** [comment]
`koch testinstall` times out Travis at just 50 mins:

https://api.travis-ci.org/v3/job/474484670/log.txt

```
progress[all]: i: 107 / 110 cat: examples
testament/tester --nim:compiler/nim pcat examples 


The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by kaushalmodi** [comment]
@Araq mentioned [here][1] that a workaround for this timeout would be to limit `koch testinstall` to run only "megatest".

[1]: https://irclogs.nim-lang.org/02-01-2019.html#17:59:19

**Comment by kaushalmodi** [comment]
Look into Travis Build Stages to see if that circumvents with timeout issue: https://gitter.im/nim-lang/Nim?at=5c2cd7e42863d8612bc9113d

**Comment by kaushalmodi** [comment]
Putting the timeout issue aside, I also see `koch testinstall` failing many tests because of "nodejs binary not in PATH".

https://api.travis-ci.org/v3/job/474484670/log.txt

```
testament/tester --nim:compiler/nim pcat arithm 
[2m[33mJOINED: [1m[36mtests/arithm/tarithm.nim C[0m
[32mPASS: [36mtests/arithm/tashr.nim C                                    [34m ( 0.83025384 secs)[0m
[1m[31mFAIL: [36mtests/arithm/tashr.nim JS[0m
[1m[36mTest "tests/arithm/tashr.nim" in category "arithm"[0m
[1m[31mFailure: reExeNotFound[0m
[33mExpected:[0m
[1m
[0m
[33mGotten:[0m
[1mnodejs binary not in PATH
[0m
FAILURE! total: 3 passed: 1 skipped: 1 failed: 1
```

**Comment by Araq** [comment]
``koch testinstall`` now works.
