### ISSUE TITLE
M1 nightly support?

### ISSUE THREAD

**Issue by QuixoticValentine** [nim-lang/nightlies#47]
Currently there is no way to download experimental M1 nim without using Rosetta to compile it yourself.

**Comment by alaviss** [comment]
Current requirements for this:

- [ ] Verify that the `clang` provided by CI build machines can cross-compile to arm64 macOS
- [ ] `koch` must be able to cross-bootstrap a compiler for a different platform, similarly for tools
- [ ] Must be able to cross-compile 3rd-party dependencies or obtain native binaries of those for arm64 macOS
