### ISSUE TITLE
Speed up brew installs

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nightlies#9]
Ref: https://gitter.im/nim-lang/Nim?at=5bde78cfcd2a6b5bdc916889

```
HOMEBREW_NO_AUTO_UPDATE=1 brew install libssh2
```

Ref: https://github.com/genotrance/nimgen/blob/ae6d4aff28559b13cec28c878209591ea3b57314/.travis.yml#L13

Thanks @genotrance.

**Comment by timotheecour** [comment]
form that chat:

> <shashlick> @kaushalmodi: nightlies builds suffer from this too - 8 extra minutes to do brew update/installs

> <shashlick> HOMEBREW_NO_AUTO_UPDATE=1 brew install libssh2 worked well - now runs in 4 seconds

i'm surprised though, if brew installed in the standard location? if so bottles should be fast? but maybe it's still slow because CI machines are slow?

**Comment by alaviss** [comment]
This is no longer an issue with the new pipeline.
